### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by Foricoso** [CrystalBear45/Sentence-ATM#2]
Hello, it seems like the addon crashes on start-up for me:
![image](https://user-images.githubusercontent.com/48365322/68387810-7edaa280-015f-11ea-8410-aa12d3f9a274.png)

**Comment by CrystalBear45** [comment]
Hmm. That is extrememly weird cause that hasn't happened to anyone. I think it might be a problem with anki itself because the "six" thing comes with anki already. So I'm comptely stumped on this issue. I'll look into it. For now, so far what have you done? Can you try uninstalling it and reinstalling it again? Sorry about that

**Comment by Foricoso** [comment]
I tried reinstalling but that doesn't fix it, I'll try messing around in the next days to see if I can notice 
something more. I just have a few more addons installed and several decks, nothing out of the ordinary.
Thanks anyway, if I can get it to work I'll let you know.

**Comment by CrystalBear45** [comment]
I’m not sure if this will fix it but can you try this? It involves just removing 2 lines of code. Go to the add on folder which starts with 1209404 and look for translations.py. Then open it with notepad and delete line 5 and 7. So delete the lines in the top which says:
f



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Foricoso** [comment]
The same error pops up on startup. I'll try installing it on a Windows 10 machine this evening (I'm trying on W7) with a clean Anki install.

**Comment by CrystalBear45** [comment]
Did you remove those 2 lines? What error are you getting now?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrystalBear45** [comment]
Hmm really sorry about this. I’ll try to come up with a solution in a couple of days. For now let me know if it works after you do everything. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Foricoso** [comment]
I already removed those 2 lines, the error just stays the same, are we talking about translations.py at 
C:\Users\USERNAME\AppData\Roaming\Anki2\addons21\1209404305
right?

**Comment by CrystalBear45** [comment]
Nvm I was wrong. I think I know the gist of what is wrong. Let me look into it for a while and Tell me if you got it working after the clean install and other things. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrystalBear45** [comment]
Figured it out, the problem really is with anki. This happened to two other people and when they reinstalled anki, it worked perfectly fine. So try that and it should work.
